python forecast_question_in_model.py 16404 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 12348 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 26721 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 14441 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 4215 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 10359 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 8313 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 14456 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 6304 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 18664 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 8509 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 10574 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 8538 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 18789 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 10614 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 8583 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 4527 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 6601 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 6604 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 10709 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 6614 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 6618 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 6615 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 4585 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 491 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 4615 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 2621 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 2622 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 4694 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 2665 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 2711 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 2729 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 21167 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 10933 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 4798 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 8909 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 10971 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 4830 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 736 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 4851 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 4873 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 8968 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 4882 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 15146 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 4927 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 841 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 4968 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 7038 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 899 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 4997 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 7054 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 7072 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 5039 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 3019 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 980 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 3054 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 3095 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 21531 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 3103 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 7207 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 7209 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 3144 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 5212 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 17519 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 17520 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 3191 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 5240 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 15490 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 7314 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 7333 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 3245 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 7383 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 9450 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 3325 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 7444 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 9496 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 5406 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 5407 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 3366 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 5423 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 7481 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 9540 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 3410 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 7509 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 17763 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 3477 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 21914 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 9734 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 1558 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 1574 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 1576 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 1579 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 3657 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 3665 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 20056 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 13922 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 15964 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 5755 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 1662 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 3733 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 20136 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 7862 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 20157 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 5875 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 12020 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 3858 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 12112 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 12117 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 28570 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 4050 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 4083 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 8186 deepseek-r1:8b-llama-distill-q4_K_M
python forecast_question_in_model.py 22523 deepseek-r1:8b-llama-distill-q4_K_M